<?php

function search($attribute, $search) {
    try {
        $db = new PDO(
            "mysql:host=" . DBHOST . "; dbname=" . DBNAME . ";charset=utf8",
            DBUSER
        );

        $valid_columns = [
            'user_id', 'first_name', 'last_name', 'email',
            'website_id', 'website_name', 'url',
            'account_id', 'username', 'passphrase', 'created_at', 'comments'
        ];

        $db->exec("SET block_encryption_mode = '". BLOCK_ENCRYPTION_MODE ."'");
        $db->exec("SET @key_str = '". KEY_STR ."'");
        $db->exec("SET @init_vector = '". INIT_VECTOR ."'");

        $search_table =
            "CREATE TEMPORARY TABLE search_table AS
            SELECT
                u.user_id,
                u.first_name,
                u.last_name,
                u.email,
                w.website_id,
                w.website_name,
                w.url,
                a.account_id,
                a.username,
                CAST(AES_DECRYPT(a.passphrase, '". KEY_STR ."', '". INIT_VECTOR ."') AS CHAR) AS passphrase,
                a.created_at,
                a.comments
            FROM account a
            INNER JOIN user u ON a.user_id = u.user_id
            INNER JOIN website w ON a.website_id = w.website_id";
        $db->exec($search_table);

        if ($attribute === 'all') {
            $conditions = [];
            foreach ($valid_columns as $column) {
                $conditions[] = "$column LIKE \"%{$search}%\"";
            }
            $where_clause = implode(' OR ', $conditions);
            $select_query = "SELECT * FROM search_table WHERE $where_clause";
        } else {
            $select_query = "SELECT * FROM search_table WHERE $attribute LIKE \"%{$search}%\"";
        }

        $statement = $db -> prepare($select_query);
        $statement -> execute();

        $results = $statement->fetchAll(PDO::FETCH_ASSOC);

        if (empty($results)) {
            echo "<p>No results found for '$search' in '$attribute'.</p>";
        } else {
            echo "<table border='1'>";
            echo "<thead><tr>";
            foreach (array_keys($results[0]) as $col) {
                echo "<th>" . htmlspecialchars($col) . "</th>";
            }
            echo "</tr></thead><tbody>";
            foreach ($results as $row) {
                echo "<tr>";
                foreach ($row as $cell) {
                    echo "<td>" . htmlspecialchars($cell ?? '') . "</td>";
                }
                echo "</tr>";
            }
            echo "</tbody></table>";
        }

    } catch( PDOException $e ) {
        echo '<p>The following message was generated by function <code>search</code>:</p>' . "\n";
        echo '<p id="error">' . $e -> getMessage() . '</p>' . "\n";
        echo "<p>There are a few reasons for this. Perhaps the database doesn’t exist or wasn’t mounted. Does the volume/drive containing the database have read and write permissions?</p>\n";
        echo '<p>Click <a href="./">here</a> to go back.</p>';

        exit;
    }
}
