<?php

function search($attribute, $search) {
    try {
        $db = new PDO(
            "mysql:host=" . DBHOST . "; dbname=" . DBNAME . ";charset=utf8",
            DBUSER
        );

        $valid_columns = [
            'user_id', 'first_name', 'last_name', 'email',
            'website_id', 'website_name', 'url',
            'username', 'passphrase', 'created_at', 'comments'
        ];

        $db->exec("SET block_encryption_mode = '". BLOCK_ENCRYPTION_MODE ."'");
        $db->exec("SET @key_str = '". KEY_STR ."'");
        $db->exec("SET @init_vector = '". INIT_VECTOR ."'");

        $search_table =
            "CREATE TEMPORARY TABLE temporary_table AS
            SELECT
                user.user_id,
                user.first_name,
                user.last_name,
                user.email,
                website.website_id,
                website.website_name,
                website.url,
                registers_for.username,
                CAST(AES_DECRYPT(registers_for.passphrase, '". KEY_STR ."', '". INIT_VECTOR ."') AS CHAR) AS passphrase,
                registers_for.created_at,
                registers_for.comments
            FROM registers_for
            INNER JOIN user ON registers_for.user_id = user.user_id
            INNER JOIN website ON registers_for.website_id = website.website_id";
        $db->exec($search_table);

        if ($attribute === 'all') {
            $conditions = [];
            foreach ($valid_columns as $column) {
                $conditions[] = "$column LIKE \"%{$search}%\"";
            }
            $where_clause = implode(' OR ', $conditions);
            $select_query = "SELECT * FROM temporary_table WHERE $where_clause";
        } else {
            $select_query = "SELECT * FROM temporary_table WHERE $attribute LIKE \"%{$search}%\"";
        }

        $statement = $db -> prepare($select_query);
        $statement -> execute();

        $results = $statement->fetchAll(PDO::FETCH_ASSOC);

        if (empty($results)) {
            echo "<p>No results found for '$search' in '$attribute'.</p>";
        } else {
            echo "<table border='1'>";
            echo "<thead><tr>";
            foreach (array_keys($results[0]) as $col) {
                echo "<th>" . htmlspecialchars($col) . "</th>";
            }
            echo "</tr></thead><tbody>";
            foreach ($results as $row) {
                echo "<tr>";
                foreach ($row as $cell) {
                    echo "<td>" . htmlspecialchars($cell ?? '') . "</td>";
                }
                echo "</tr>";
            }
            echo "</tbody></table>";

            $row_count = count($results);
            echo "<p>Total number of results: $row_count</p>";
        }

    } catch( PDOException $e ) {
        echo '<p>The following message was generated by function <code>search</code>:</p>' . "\n";
        echo '<p id="error">' . $e -> getMessage() . '</p>' . "\n";
        echo "<p>There are a few reasons for this. Perhaps the database doesn’t exist or wasn’t mounted. Does the volume/drive containing the database have read and write permissions?</p>\n";
        echo '<p>Click <a href="./">here</a> to go back.</p>';

        exit;
    }
}

function update($current_attribute, $new_attribute, $query_attribute, $pattern) {
    try {
        $db = new PDO(
            "mysql:host=" . DBHOST . "; dbname=" . DBNAME . ";charset=utf8",
            DBUSER
        );

        $search_table=
            "UPDATE registers_for
            JOIN user USING (user_id)
            JOIN website USING (website_id)
            SET {$current_attribute}=\"{$new_attribute}\"
            WHERE {$query_attribute}=\"{$pattern}\"";

        $statement = $db -> prepare($search_table);
        $statement -> execute();

        if ($statement->rowCount() > 0) {
            echo '<p>Attribute updated successfully.</p>';
        } else {
            echo '<p id="error">No records matched the specified pattern. No update was made.</p>';
        }

    } catch( PDOException $e ) {
        echo '<p>The following message was generated by function <code>update</code>:</p>' . "\n";
        echo '<p id="error">' . $e -> getMessage() . '</p>' . "\n";

        exit;
    }
}

function insert($website_url, $email, $username, $passphrase, $comment) {
    try {
        $db = new PDO(
            "mysql:host=" . DBHOST . "; dbname=" . DBNAME . ";charset=utf8",
            DBUSER
        );

        $db->exec("SET block_encryption_mode = '". BLOCK_ENCRYPTION_MODE ."'");
        $db->exec("SET @key_str = '". KEY_STR ."'");
        $db->exec("SET @init_vector = '". INIT_VECTOR ."'");

        $user_query = "SELECT user_id, first_name, last_name FROM user WHERE email = :email";
        $user_statement = $db->prepare($user_query);
        $user_statement->execute(['email' => $email]);
        $user = $user_statement->fetch(PDO::FETCH_ASSOC);

        if (!$user) {
            echo '<p id="error">User does not exist.</p>';
            return;
        }

        $user_id = $user['user_id'];
        $first_name = $user['first_name'];
        $last_name = $user['last_name'];

        $website_query = "SELECT website_id, website_name FROM website WHERE url = :url";
        $website_statement = $db->prepare($website_query);
        $website_statement->execute(['url' => $website_url]);
        $website = $website_statement->fetch(PDO::FETCH_ASSOC);

        if (!$website) {
            echo '<p id="error">Website does not exist.</p>';
            return;
        }

        $website_id = $website['website_id'];
        $website_name = $website['website_name'];

        $encrypted_passphrase = $db->query("SELECT AES_ENCRYPT('$passphrase', @key_str, @init_vector)")->fetchColumn();

        $insert_query = "
            INSERT INTO registers_for (website_id, user_id, username, passphrase, created_at, comments)
            VALUES (:website_id, :user_id, :username, :passphrase, NOW(), :comments)";

        $statement = $db->prepare($insert_query);

        $statement->execute([
            'website_id' => $website_id,
            'user_id' => $user_id,
            'username' => $username,
            'passphrase' => $encrypted_passphrase,
            'comments' => $comment
        ]);

        if ($statement->rowCount() > 0) {
            echo '<p>New entry added successfully!</p>';
        } else {
            echo '<p id="error">Failed to add new entry.</p>';
        }

    } catch(PDOException $e) {
        echo '<p>The following message was generated by function <code>insert</code>:</p>' . "\n";
        echo '<p id="error">' . $e -> getMessage() . '</p>' . "\n";

        exit;
    }
}
